version: '3'

services:
  system-gift-point:
    image: simple-project/system-gift-point:0.1.0
    platform: linux/amd64
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    environment:
      - PORT_APP=8080
      - DB_DSN=host=postgres user=root password=secret dbname=system_gift_point port=5432
      - APP_NAME=system-gift-point
      - GO_ENV=DEV
    ports:
      - 8080:8080
    depends_on:
      - postgres

    
  postgres:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_DB: system_gift_point
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_SSL_MODE: disable
    ports:
      - 54322:5432
    volumes:
      - pg-data-point:/var/lib/postgresql/data

volumes:
  pg-data-point: