version: '3'

services:
  favourite-book:
    image: simple-project/favourite-book:0.1.0
    platform: linux/amd64
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    environment:
      - PORT_APP=8080
      - DB_DSN=host=postgres user=root password=secret dbname=favourite_book port=5432
      - APP_NAME=favourite-book
      - GO_ENV=DEV
    ports:
      - 8080:8080
    depends_on:
      - postgres

    
  postgres:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_DB: favourite_book
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_SSL_MODE: disable
    ports:
      - 54322:5432
    volumes:
      - pg-data-book:/var/lib/postgresql/data

volumes:
  pg-data-book: